name: Publish to TestPyPI

on:
  release:
    types: [prereleased]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    name: Build and publish (TestPyPI)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # for TestPyPI Trusted Publishing (OIDC)
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist and wheel
        run: |
          python -m build --sdist --wheel

      - name: Publish to TestPyPI (OIDC trusted publisher)
        if: ${{ secrets.TEST_PYPI_API_TOKEN == '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: Publish to TestPyPI (API token)
        if: ${{ secrets.TEST_PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          skip-existing: true

